
[teams]
webhookUrl = "https://fielyca50k.execute-api.eu-west-3.amazonaws.com/prod/webhook/generic-applicative"
channelId = "ELITE_LEGACY_MEERO"
apiKey = "kbusiCe7537PZeP623fuN52XXSXDNlQQ8PrNkc9E"

[update_customer_dispo.teams]
webhookUrl = "https://fielyca50k.execute-api.eu-west-3.amazonaws.com/prod/webhook/generic-applicative"
channelId = "ELITE_LEGACY_MEERO"
apiKey = "kbusiCe7537PZeP623fuN52XXSXDNlQQ8PrNkc9E"

[sync_fo_quotations.teams]
webhookUrl = "https://fielyca50k.execute-api.eu-west-3.amazonaws.com/prod/webhook/generic-applicative"
channelId = "ELITE_LEGACY_MEERO"
apiKey = "kbusiCe7537PZeP623fuN52XXSXDNlQQ8PrNkc9E"
