
[update_customer_dispo.algolia]
appId = "2IADKFQCGN"
apiKey = "5fcaf1dbd539cf76c630c3fa0a748b78"
indexName = "prod_ELITE_OFFERS"

[update_customer_dispo.customerDispo]
dryRun = true
dryRunNotify = true

[zero_km.websocket]
port = 21003