[package]
org = "cosmobilis"
name = "update_customer_dispo"
version = "0.1.0"
distribution = "2201.12.7"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "cosmobilis"
name = "job_patch"
version = "0.1.0"
repository = "local"
